export default function sitemap() {
  return [
    {
      url: "https://khani.co.uk/",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 1,
    },
    {
      url: "https://khani.co.uk/useful-guides",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/french-bulldog-curiosity",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/when-deworming-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/dog-spur",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/dont-let-a-dog-bark-on-a-walk",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/dogs-that-dont-bark",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/abrasions-on-dogs-paw-pads",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/labrador-dachshund-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/golden-retriever-cocker-spaniel-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/beagle-golden-retriever-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/golden-retriever-poodle-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/golden-retriever-spitz-crossbreed",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/pitbull-german-shepherd-crossbreed",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/differences-poodle-toy-miniature",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/dalmatian-golden-retriever-crossbreed",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/golden-retriever-dachshund",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/newfoundland-golden-mix",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/chihuahua-spitz-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/pinscher-chihuahua-mix",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/yorkshire-terrier-chihuahua-mix",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/yorkshire-poodle-crossbreed",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/poodle-chihuahua-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/the-lagotto-romagnolo",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/difference-between-lagotto-and-poodle",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/bedlington-terrier",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/australian-terrier",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/husky-labrador-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/labrador-german-shepherd-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/labrador-maremma-crossbreed",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/labrottie",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/labrabull",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/malinois-golden-retriever-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/golden-retriever-setter-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/german-shepherd-golden-retriever-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/czechoslovakian-wolfdog-golden-retriever-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/belgian-shepherd-golden-retriever-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/spinone-golden-retriever-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/border-collie-golden-crossbreed",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/irish-setter-golden-retriever-crossbreed",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/husky-golden-retriever-crossbreed",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/labrador-golden-retriever-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/golden-retriever-maremma-sheepdog-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/rottweiler-golden-retriever-mix",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/golden-retriever-pitbull-mix",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/golden-bernese-mountain-dog-mix",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/rottweiler-dogo-argentino-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/intersection-corso-dogo-argentino",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/maremma-sheepdog-border-collie-mix",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/border-collie-australian-shepherd",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/bergamo-border-collie-crossbreed",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/border-collie-german-shepherd-mix",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/airedale-terrier",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/differences-amstaff-pitbull",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://khani.co.uk/diet/salami-for-dogs",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/fat-of-the-ham-to-the-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/cat-food-for-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/can-dogs-eat-tomatoes",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/can-dogs-eat-mushrooms",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/health/gastritis-in-the-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/the-dog-trembles",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/health/how-to-tell-if-dog-has-fever",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-diarrhea",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/health/pancreatitis-in-the-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/fat-of-the-ham-to-the-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/proteins-for-dogs",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/garlic-to-the-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/onion-to-the-dogs",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/health/vomiting-in-the-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/cross-breed-labrador-hunting-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/boxer-labrador-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/amstaff-labrador-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/jack-russell-labrador-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/dalmatian-labrador-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/labrador-corso-cross",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/health/dogs-blood-stools",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/health/dogs-kidney-failure",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/seasoning-rice-for-the-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/potatoes-to-the-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/dog-scratches-without-fleas",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/how-much-should-a-dog-eat",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/grain-free-croquettes",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/grain-free-croquettes",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/dandie-dinmont-terrier",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/cairn-terrier",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/products/gps-for-dogs",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/health/knee-dysplasia",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/fish-oil-for-dogs",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/changing-dogs-diet",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/health/diabetes-in-dogs",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/the-homemade-diet-for-the-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/dog-ear-cleaning",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/how-to-trim-your-dogs-nails",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/how-to-clean-a-dogs-teeth",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/health/dogs-teeth-scaling",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/australian-silky-terrier",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/biewer-terrier",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/poodle",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/jack-russell-terrier",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/vegetables-for-dogs",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/dogs-can-eat-fish",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/barf-diet",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/how-to-apply-frontline",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/perfuming-a-dog-without-washing-it",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/removing-the-odor-from-the-fur",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/the-colours-of-the-poodle",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/health/symptoms-of-canine-dysplasia",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/truffle-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/poodle-haircuts",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/the-homemade-diet-for-the-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/toy-poodle-or-miniature-poodle",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/poodle-grooming",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/grooming-of-the-lagotto",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/health/dermatitis-in-dogs",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/health/hip-dysplasia-in-dogs",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/health/allergy-to-dog-hair",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/big-dogs/large-poodle",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/health/treating-colitis-in-dogs",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/yorkshire-maltese-crossbreed",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/washing-the-dog-at-home",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/dog-training",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/maltese-13-things",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/which-countries-fci",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/barking-dog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/dogs-lick-owners",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/dogs-dream",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/dog-grooming",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/dog-eating-faeces",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/59-curiosities-about-dogs-part-1",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/curiosity-part-2",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.it/cane-che-abbaia/",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/french-bulldog-diseases",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/washing-the-french-bulldog-at-home",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/the-colours-of-the-french-bulldog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/frequently-asked-questions-about-the-poodle",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/why-choose-a-poodle",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/grooming-of-the-maltese",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/hairless-dogs",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/dogs-at-the-sea",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/to-clip-the-dog-yes-or-no",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/dog-not-eating",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/useful-guides/ideal-dogs-for-children",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/miniature-bull-terrier",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/miniature-poodle-crosses",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/dog-breeds/small-dogs/the-chihuahua",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/dog-diet-pancreatitis",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://khani.co.uk/diet/dog-feeding-liver-problems",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
  ];
}
